### ISSUE TITLE
Implement validation for CandidateTimeSlot

### ISSUE THREAD

**Issue by Ewentualnie** [Mo-og/intellistart-java-2022-debuggers#55]
Implement time validation for CandidateTimeSlot:

- `to` - `from`  period must be >= 1.5h

- Time period must be rounded to 30 minutes 

- `from` must not be earlier than 8:00 AM and `to` - later than 10:00 PM

- Time period must not overlap other candidate slots

If time period is incorrect or slot overlaps throw appropriate exceptions.

**Comment by holeksii** [comment]
Done
